name: Prettier + ESLint

on: 
  push:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run Prettier
        run: git diff --name-only --diff-filter=ACMRT origin/main HEAD | xargs -r npx prettier --check --ignore-unknown
      - name: Run ESLint
        run: git diff --name-only --diff-filter=ACMRT origin/main HEAD | xargs -r npx eslint --check --ignore-unknown
